package com.stkj.cashier.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stkj.cashier.bean.db.CompanyMemberdbEntity;
import com.stkj.cashier.cbgfacepass.model.FacePassPeopleInfo;

import com.stkj.cashier.greendao.CompanyMemberdbEntityDao;
import com.stkj.cashier.greendao.FacePassPeopleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyMemberdbEntityDaoConfig;
    private final DaoConfig facePassPeopleInfoDaoConfig;

    private final CompanyMemberdbEntityDao companyMemberdbEntityDao;
    private final FacePassPeopleInfoDao facePassPeopleInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyMemberdbEntityDaoConfig = daoConfigMap.get(CompanyMemberdbEntityDao.class).clone();
        companyMemberdbEntityDaoConfig.initIdentityScope(type);

        facePassPeopleInfoDaoConfig = daoConfigMap.get(FacePassPeopleInfoDao.class).clone();
        facePassPeopleInfoDaoConfig.initIdentityScope(type);

        companyMemberdbEntityDao = new CompanyMemberdbEntityDao(companyMemberdbEntityDaoConfig, this);
        facePassPeopleInfoDao = new FacePassPeopleInfoDao(facePassPeopleInfoDaoConfig, this);

        registerDao(CompanyMemberdbEntity.class, companyMemberdbEntityDao);
        registerDao(FacePassPeopleInfo.class, facePassPeopleInfoDao);
    }
    
    public void clear() {
        companyMemberdbEntityDaoConfig.clearIdentityScope();
        facePassPeopleInfoDaoConfig.clearIdentityScope();
    }

    public CompanyMemberdbEntityDao getCompanyMemberdbEntityDao() {
        return companyMemberdbEntityDao;
    }

    public FacePassPeopleInfoDao getFacePassPeopleInfoDao() {
        return facePassPeopleInfoDao;
    }

}
